### ISSUE TITLE
bitcast causing an abort during codegen for map cell insertion

### ISSUE THREAD

**Issue by gtrepta** [runtimeverification/llvm-backend#488]
Issue from runtimeverification/avm-semantics#11

These semantics are trying to generate a multiplicity cell of type Map in the RHS using a function rule, and the code generator seems to be messing up the llvm typing for it.

```
void (%map*, %block*, %block*)* bitcast (void (%map*, %map*, %map*)* @hook_MAP_concat to void (%map*, %block*, %block*)*)
```

Attached definition.kore: [definition.zip](https://github.com/runtimeverification/llvm-backend/files/8099246/definition.zip)

**Comment by gtrepta** [comment]
```
module A
  imports INT

  configuration
    <k> $PGM:K </k>
    <cells>
      <cell multiplicity="*" type="Map">
        <num> 0 </num>
      </cell>
    </cells>

    syntax CellCell ::= #makeCell( Int ) [function]
 // -----------------------------------------------
    rule #makeCell( X ) => (<cell> <num> X </num> </cell>)

    syntax KItem ::= "#putCells"
 // ----------------------------
    rule <k> #putCells => . ... </k>
         <cells>
           (.Bag => #makeCell(0))
           ...
         </cells>

endmodule
```

**Comment by theo25** [comment]
I did some investigation and the issue arises from here:
```
         <cells>
           (.Bag => #makeCell(0))
           ...
         </cells>
```
The backend implements this as a call the the `MAP.concat` hook with arguments of types `%block *, %map*` instead of `%map*, %map*`. The wrongly typed argument comes from an injection from `SortCellCell` to `SortCellCellMap` for which the llvm backend generates a `%block*` value its result.
