### ISSUE TITLE
Implement `k-rule-find`

### ISSUE THREAD

**Issue by Baltoli** [runtimeverification/llvm-backend#702]
Per https://github.com/runtimeverification/k/issues/3180, we want to expose "why doesn't this rule apply" as a standalone feature, rather than something that only GDB / LLDB have access to.

We should implement a tool that consumes the LLVM backend's match log to expose this at the command line.

It might also be possible to expose a single function that GDB / LLDB can call into and get match failures printed, rather than having the Python code re-implement the logic.

**Comment by dwightguth** [comment]
The llvm backend, when built with debugging enabled, generates certain code that can be used to tell you whether a rule should apply to a given term and why it doesn't if it doesn't. We just want to expose this functionality as a standalone tool.

Essentially we need to do the following:

1. Modify the code generator to generate an llvm function that takes a filename, a line number, an optional column number, and a term, and, based on the filename, line number, and column number, calls the functions called by gdb for each rule at that location in the source code. There may be more than one rule with a given location, so we want to call the relevant code for each one. This function can just abort if we aren't generating the decision trees for the match log. One additional note: compare filenames by checking whether the absolute path to the file contains the specified filename as a suffix. This means if the user doesn't specify the full path, there might be multiple matching filenames, and again, we ought to select all rules that match.
2. Create a tool frontend that takes a filename containing a kore term and a filename location tuple of the form <file>:<line> or <file>:<line>:<column> and parses the kore term into the internal term representation, then parses the location tuple and calls the function that was generated by the code generator. Then it needs to read out the contents of the log generated and print it using the same logic as the gdb script. Put the logic for printing the match log in the runtime library because we may want to refactor the gdb code to call it directly.

**Comment by Robertorosmaninho** [comment]
The first part of this issue should be to implement the tool's frontend with the following design:

### The CLI structure

```bash
k-rule-find <filename> <location> <path_to_shared_lib>
```

- Filename: The filename of a kore term in a file.
- location: A tuple with the k definition file and the line:column of the rule function we expect to match as: `filename.k:line:column`.
- Path: The shared library's path containing the llvm match functions (second part).

### The workflow

- First, the tool parses the `KTerm` inside the given file to `block*` so it can be interpreted properly as KORE Symbol.
- Second, call `dlopen` to open the shared library that contains the llvm match functions.
- Get the llvm function to want to check if it matches with the given `KTerm` on the shared library with `dlsym`.
- Call the llvm function with the proper arguments. Ex:
    - `llvm_match_function(kterm_symbol, kdefinition_filename,line, column);`
- The llvm function should call a runtime function that prints for the user “Match succeeds” or “Subject: … does not match pattern: …”

**Comment by Robertorosmaninho** [comment]
Extra feature: tag derived healing and cooling rules as well.

**Comment by ehildenb** [comment]
Why does `k-rule-find` need access to the `<path_to_shared_lib>`? That does not seem to make sense to me, it should be able to just return the unique rule ID of the rule at that location.

Then `k-rule-apply` should be the one that actually needs access to that lib.

**Comment by Robertorosmaninho** [comment]
@ehildenb, the tools were being implemented together, but I've already corrected it. My last commit has an implementation for the required `k-rule-find`. The only difference is that it returns the rule label instead of its unique ID. The idea is to use the rule label as input for the `k-rule-apply`.
