### ISSUE TITLE
Expose "safely evaluate partial function" binding

### ISSUE THREAD

**Issue by Baltoli** [runtimeverification/llvm-backend#925]
It would be useful for the [booster to be able to use the LLVM backend to evaluate partial functions where all the function's arguments are concrete](https://github.com/runtimeverification/hs-backend-booster/issues/415); however, the current design of the function evaluator in the backend just ends up calling `abort` when a partial function is evaluated, which crashes the host process (`kore-rpc`).

We should implement a refactored version of [`abortWhenStuck`](https://github.com/runtimeverification/llvm-backend/blob/e8c7319292ad82f7ca93e0faa4aa99656104cc17/lib/codegen/Decision.cpp#L798-L848) that instead of crashing the process, returns a sentinel value[^1] to the caller. Note that the existing behaviour would be subsumed by this; we can implement it by calling the partial-safe version, then checking for the sentinel value and aborting if it's returned.

Clients that want the abort-safe behaviour can then have the internal evaluator exposed as a new binding.

[^1]: I vaguely recall that `nullptr` isn't valid here; perhaps we want to distinguish a particular term representation that signals failure.

**Comment by goodlyrottenapple** [comment]
This was another point, recently, where an error type would maybe be helpful: https://github.com/runtimeverification/llvm-backend/blob/eeccaebaed784a40f17971bf9f1028b07c510537/runtime/util/ConfigurationParser.cpp#L36-L39

This instance wasn't a pressing issue, because the cause was a mismatch between the llvm library version and the kore file loaded in the booster, which is probably a good reason to completely abort execution, but perhaps might be better if the calling code was allowed to handle this error.

**Comment by Baltoli** [comment]
That one's trickier, because calls to `getTagForSymbolName` are so ubiquitous throughout the generated code; the bound code isn't usually _directly_ calling it (if that were the case, propagating the error would be easier). We would probably need to redesign big chunks of the backend to have a global error recovery mechanism to handle it.

**Comment by goodlyrottenapple** [comment]
Fair enough, this one probably wouldn't be that important

**Comment by Baltoli** [comment]
We can probably implement this now, at least for the booster via the C API: #955
