### ISSUE TITLE
Unsound/invalid rewrite in the LLVM backend

### ISSUE THREAD

**Issue by virgil-serbanuta** [runtimeverification/llvm-backend#930]
The LLVM backend changes cells that should not change when rewriting.

Version:
```
kompile --version
K version:    v6.1.37-0-g9a8e220ade
Build date:   Jo dec 07 19:00:09 EET 2023
```

To reproduce:
a.k
```
module A-SYNTAX
    syntax KItem  ::= "a"
endmodule

module A
    imports A-SYNTAX
    imports BYTES
    imports INT-SYNTAX

    configuration
      <test>
        <k> $PGM </k>
        <mem> .Bytes </mem>
        <stuff> .Bytes </stuff>
      </test>

    syntax KItem ::= "b" | "c" | "d" | "e"

    rule <k> a => b </k>
        <mem> _ => b"alice" </mem>
    rule <k> b => c </k>
        <mem> B </mem>
        <stuff> _ => B </stuff>
    rule <k> c => d </k>
        <mem> B => replaceAtBytes(B, 0:Int, b"bob__") </mem>
endmodule
```

start:
```
a
```

command line:
```
kompile a.k && krun start
```

Output:
```
<test>
  <k>
    d ~> .
  </k>
  <mem>
    b"bob__"
  </mem>
  <stuff>
    b"bob__"
  </stuff>
</test>
```

Expected:
```
<test>
  <k>
    d ~> .
  </k>
  <mem>
    b"bob__"
  </mem>
  <stuff>
    b"alice"
  </stuff>
</test>
```

**Comment by virgil-serbanuta** [comment]
This is blocking the CoinDrip property test for Elrond.

**Comment by dwightguth** [comment]
The llvm backend uses a mutable representation of the `Bytes` sort because it's vastly more efficient over the subset of definitions that it supports. What is happening is that the object in the `mem` and `stuff` cell is the same reference and thus when `replaceAt` writes to that location, both terms get modified. The solution is to perform a copy of the Bytes object when it appears more than once on the rhs of a rule. One way you can do this is to concatenate a `Bytes` object with the empty byte string.

**Comment by virgil-serbanuta** [comment]
Ok, thanks, I'll try that. Will the LLVM backend be fixed do the copy itself one way or another (e.g. perhaps by not sharing mutable objects, or by doing copy-on-write), or do I need to implement a permanent workaround for this?

**Comment by Baltoli** [comment]
After a couple of attempts to fix this, I think the solution will need to be two divergent implementations of the Bytes hooks hidden behind a compiler flag.
